scripts:
  - java -version
  - echo "JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
  - echo "JAVA_OPTS=$JAVA_OPTS"
  - echo "GRADLE_OPTS=$GRADLE_OPTS"
  - flutter pub get
  - cat android/gradle.properties
  - flutter build apk --release
