scripts:
  - unset JAVA_TOOL_OPTIONS
  - unset _JAVA_OPTIONS
  - unset JAVA_OPTS
  - unset GRADLE_OPTS
  - echo "Checking Java variables"
  - env | grep -i java
  - flutter pub get
  - flutter build apk --release
